service: cys-serverless-todos
provider:
  name: aws
  runtime: nodejs12.x
functions:
  todos:
    handler: handler.todos
    layers:
      - arn:aws:lambda:us-east-1:378338563722:layer:logging:2
    events:
      - http:
          path: todos
          method: get
